# Let's define the exact list of 84 sound effects with their rough timestamps from the video
sfx_definitions = [
    {"id": 1, "approx_ts": 0.5, "name": "Bonk / Whack", "filename": "01_bonk_impact.mp3", "cat": "Cartoon SFX"},
    {"id": 2, "approx_ts": 1.2, "name": "What Meme", "filename": "02_what_meme.mp3", "cat": "Voice Meme"},
    {"id": 3, "approx_ts": 2.5, "name": "Pencil Writing", "filename": "03_pencil_scratch.mp3", "cat": "Foley"},
    {"id": 4, "approx_ts": 3.8, "name": "Camera Shutter Flash", "filename": "04_camera_shutter.mp3", "cat": "Foley"},
    {"id": 5, "approx_ts": 4.8, "name": "Mouse Click", "filename": "05_mouse_click.mp3", "cat": "Foley"},
    {"id": 6, "approx_ts": 6.4, "name": "Nope (TF2 Engineer)", "filename": "06_nope_engineer.mp3", "cat": "Voice Meme"},
    {"id": 7, "approx_ts": 8.0, "name": "Loud Scream", "filename": "07_loud_scream.mp3", "cat": "Reaction"},
    {"id": 8, "approx_ts": 10.8, "name": "Cartoon Spring Boing", "filename": "08_cartoon_spring_boing.mp3", "cat": "Cartoon SFX"},
    {"id": 9, "approx_ts": 14.5, "name": "Yay Children Cheering", "filename": "09_yay_children_cheer.mp3", "cat": "Reaction"},
    {"id": 10, "approx_ts": 17.8, "name": "Cash Register Ka-Ching", "filename": "10_cash_register_kaching.mp3", "cat": "Foley"},
    {"id": 11, "approx_ts": 19.1, "name": "Bruh", "filename": "11_bruh.mp3", "cat": "Voice Meme"},
    {"id": 12, "approx_ts": 20.5, "name": "Are You Serious My Brother", "filename": "12_are_you_serious_my_brother.mp3", "cat": "Voice Meme"},
    {"id": 13, "approx_ts": 26.0, "name": "Angelic Choir (Halo Theme)", "filename": "13_angelic_halo_choir.mp3", "cat": "Music / Riff"},
    {"id": 14, "approx_ts": 31.5, "name": "Punch / Slap Impact", "filename": "14_punch_slap_impact.mp3", "cat": "Impact"},
    {"id": 15, "approx_ts": 33.2, "name": "Short Scream Aah", "filename": "15_short_scream_aah.mp3", "cat": "Reaction"},
    {"id": 16, "approx_ts": 34.5, "name": "Hey Yo What The Fuck", "filename": "16_hey_yo_what_the_fuck.mp3", "cat": "Voice Meme"},
    {"id": 17, "approx_ts": 35.8, "name": "Baba Booey", "filename": "17_baba_booey.mp3", "cat": "Voice Meme"},
    {"id": 18, "approx_ts": 38.5, "name": "Baby Crying", "filename": "18_baby_crying.mp3", "cat": "Reaction"},
    {"id": 19, "approx_ts": 41.0, "name": "Sigh / Yawn", "filename": "19_sigh_yawn.mp3", "cat": "Reaction"},
    {"id": 20, "approx_ts": 43.5, "name": "Bro Really About To", "filename": "20_bro_really_about_to.mp3", "cat": "Voice Meme"},
    {"id": 21, "approx_ts": 46.2, "name": "Boy If You Don't Get", "filename": "21_boy_if_you_dont_get.mp3", "cat": "Voice Meme"},
    {"id": 22, "approx_ts": 50.0, "name": "Ayo The Pizza Here (My Ears Burn)", "filename": "22_ayo_the_pizza_here.mp3", "cat": "Voice Meme"},
    {"id": 23, "approx_ts": 54.0, "name": "Goofy Laugh", "filename": "23_goofy_laugh.mp3", "cat": "Reaction"},
    {"id": 24, "approx_ts": 57.0, "name": "Evil Villain Laugh", "filename": "24_evil_villain_laugh.mp3", "cat": "Reaction"},
    {"id": 25, "approx_ts": 61.8, "name": "I Can't Let You Get Close", "filename": "25_i_cant_let_you_get_close.mp3", "cat": "Voice Meme"},
    {"id": 26, "approx_ts": 63.5, "name": "Green Giant", "filename": "26_green_giant.mp3", "cat": "Voice Meme"},
    {"id": 27, "approx_ts": 67.5, "name": "Please Man I Need This (Homeless)", "filename": "27_please_man_i_need_this.mp3", "cat": "Voice Meme"},
    {"id": 28, "approx_ts": 72.8, "name": "Fart Sound 1", "filename": "28_fart_sound_1.mp3", "cat": "Cartoon SFX"},
    {"id": 29, "approx_ts": 77.3, "name": "Fart Sound 2", "filename": "29_fart_sound_2.mp3", "cat": "Cartoon SFX"},
    {"id": 30, "approx_ts": 81.5, "name": "Fart With Reverb", "filename": "30_fart_with_reverb.mp3", "cat": "Cartoon SFX"},
    {"id": 31, "approx_ts": 87.0, "name": "Gun Cock / Click", "filename": "31_gun_cock_click.mp3", "cat": "Foley"},
    {"id": 32, "approx_ts": 88.5, "name": "Fatality (Mortal Kombat)", "filename": "32_fatality_mortal_kombat.mp3", "cat": "Gaming"},
    {"id": 33, "approx_ts": 91.5, "name": "FBI Open Up (Breach & Gunfire)", "filename": "33_fbi_open_up.mp3", "cat": "Voice Meme"},
    {"id": 34, "approx_ts": 95.0, "name": "Gotcha Bitch", "filename": "34_gotcha_bitch.mp3", "cat": "Voice Meme"},
    {"id": 35, "approx_ts": 99.0, "name": "Punch / Body Hit", "filename": "35_punch_body_hit.mp3", "cat": "Impact"},
    {"id": 36, "approx_ts": 105.0, "name": "Ha Gaaaay", "filename": "36_ha_gaaaay.mp3", "cat": "Voice Meme"},
    {"id": 37, "approx_ts": 108.0, "name": "Got 'Em", "filename": "37_got_em.mp3", "cat": "Voice Meme"},
    {"id": 38, "approx_ts": 110.0, "name": "Heartbeat", "filename": "38_heartbeat.mp3", "cat": "Foley"},
    {"id": 39, "approx_ts": 114.0, "name": "On The People", "filename": "39_on_the_people.mp3", "cat": "Voice Meme"},
    {"id": 40, "approx_ts": 119.5, "name": "He Needs Some Milk", "filename": "40_he_needs_some_milk.mp3", "cat": "Voice Meme"},
    {"id": 41, "approx_ts": 123.5, "name": "Hold Up Wait A Minute Something Ain't Right", "filename": "41_hold_up_wait_a_minute.mp3", "cat": "Voice Meme"},
    {"id": 42, "approx_ts": 126.2, "name": "I Like Ya Cut G (Slap)", "filename": "42_i_like_ya_cut_g.mp3", "cat": "Voice Meme"},
    {"id": 43, "approx_ts": 128.8, "name": "I'm Fast As Fuck Boy", "filename": "43_im_fast_as_fuck_boy.mp3", "cat": "Voice Meme"},
    {"id": 44, "approx_ts": 130.9, "name": "Kobe", "filename": "44_kobe.mp3", "cat": "Voice Meme"},
    {"id": 45, "approx_ts": 132.5, "name": "Hey Voice", "filename": "45_hey_voice.mp3", "cat": "Voice Meme"},
    {"id": 46, "approx_ts": 134.5, "name": "Let's Do This", "filename": "46_lets_do_this.mp3", "cat": "Voice Meme"},
    {"id": 47, "approx_ts": 150.0, "name": "Look At This Dude (Wheezing Laugh)", "filename": "47_look_at_this_dude_wheeze.mp3", "cat": "Voice Meme"},
    {"id": 48, "approx_ts": 164.0, "name": "Gun Reload / Cock", "filename": "48_gun_reload.mp3", "cat": "Foley"},
    {"id": 49, "approx_ts": 165.0, "name": "Subtle Bass Drop / 808 Thud", "filename": "49_subtle_bass_drop.mp3", "cat": "Impact"},
    {"id": 50, "approx_ts": 166.0, "name": "Record Scratch", "filename": "50_record_scratch.mp3", "cat": "Cartoon SFX"},
    {"id": 51, "approx_ts": 167.0, "name": "Windows XP Error Ding", "filename": "51_windows_xp_error.mp3", "cat": "Gaming / Tech"},
    {"id": 52, "approx_ts": 169.0, "name": "Coin / Mario Chime", "filename": "52_mario_coin.mp3", "cat": "Gaming"},
    {"id": 53, "approx_ts": 170.8, "name": "Cartoon Slip / Whoosh", "filename": "53_cartoon_slip_whoosh.mp3", "cat": "Cartoon SFX"},
    {"id": 54, "approx_ts": 173.5, "name": "Sad Violin (Womp Womp)", "filename": "54_sad_violin.mp3", "cat": "Music / Riff"},
    {"id": 55, "approx_ts": 176.5, "name": "Wilhelm Scream", "filename": "55_wilhelm_scream.mp3", "cat": "Reaction"},
    {"id": 56, "approx_ts": 179.0, "name": "Car Horn (Beep Beep)", "filename": "56_car_horn_beep_beep.mp3", "cat": "Foley"},
    {"id": 57, "approx_ts": 180.0, "name": "Clock Ticking", "filename": "57_clock_ticking.mp3", "cat": "Foley"},
    {"id": 58, "approx_ts": 182.0, "name": "Footsteps", "filename": "58_footsteps.mp3", "cat": "Foley"},
    {"id": 59, "approx_ts": 183.5, "name": "Door Creak / Close", "filename": "59_door_creak_close.mp3", "cat": "Foley"},
    {"id": 60, "approx_ts": 185.0, "name": "Phone Ring / Notification", "filename": "60_phone_ring_notification.mp3", "cat": "Foley"},
    {"id": 61, "approx_ts": 187.5, "name": "Punch / Thud", "filename": "61_punch_thud.mp3", "cat": "Impact"},
    {"id": 62, "approx_ts": 188.5, "name": "Ooh Okay", "filename": "62_ooh_okay.mp3", "cat": "Voice Meme"},
    {"id": 63, "approx_ts": 190.0, "name": "Water Drip / Plop", "filename": "63_water_drip_plop.mp3", "cat": "Foley"},
    {"id": 64, "approx_ts": 191.0, "name": "Laser / Pew Pew", "filename": "64_laser_pew_pew.mp3", "cat": "Cartoon SFX"},
    {"id": 65, "approx_ts": 193.5, "name": "Metal Pipe Falling (Clang)", "filename": "65_metal_pipe_falling.mp3", "cat": "Meme SFX"},
    {"id": 66, "approx_ts": 195.9, "name": "Ding / Service Bell", "filename": "66_ding_bell.mp3", "cat": "Foley"},
    {"id": 67, "approx_ts": 196.8, "name": "Really Nigga", "filename": "67_really_nigga.mp3", "cat": "Voice Meme"},
    {"id": 68, "approx_ts": 198.8, "name": "Pop / Cork", "filename": "68_pop_cork.mp3", "cat": "Cartoon SFX"},
    {"id": 69, "approx_ts": 200.5, "name": "Children Cheering (Yay)", "filename": "69_children_cheering_yay.mp3", "cat": "Reaction"},
    {"id": 70, "approx_ts": 202.8, "name": "Suspense / Dun Dun Dun", "filename": "70_suspense_dun_dun_dun.mp3", "cat": "Music / Riff"},
    {"id": 71, "approx_ts": 204.0, "name": "Sike Sike", "filename": "71_sike_sike.mp3", "cat": "Voice Meme"},
    {"id": 72, "approx_ts": 206.3, "name": "Anime Wow", "filename": "72_anime_wow.mp3", "cat": "Meme SFX"},
    {"id": 73, "approx_ts": 207.4, "name": "Censor Bleep", "filename": "73_censor_bleep.mp3", "cat": "Cartoon SFX"},
    {"id": 74, "approx_ts": 209.5, "name": "Airhorn MLG", "filename": "74_airhorn_mlg.mp3", "cat": "Meme SFX"},
    {"id": 75, "approx_ts": 212.0, "name": "Vine Boom (Dramatic Boom)", "filename": "75_vine_boom.mp3", "cat": "Meme SFX"},
    {"id": 76, "approx_ts": 213.0, "name": "Giggle / Snicker", "filename": "76_giggle_snicker.mp3", "cat": "Reaction"},
    {"id": 77, "approx_ts": 214.5, "name": "Buzzer (Wrong Answer)", "filename": "77_buzzer_wrong.mp3", "cat": "Gaming / Show"},
    {"id": 78, "approx_ts": 216.2, "name": "Snore (Mimimimi)", "filename": "78_snore_mimimimi.mp3", "cat": "Cartoon SFX"},
    {"id": 79, "approx_ts": 218.0, "name": "Correct Ding / Chime", "filename": "79_correct_ding.mp3", "cat": "Gaming / Show"},
    {"id": 80, "approx_ts": 220.0, "name": "Cat Screaming Meow", "filename": "80_cat_screaming_meow.mp3", "cat": "Reaction"},
    {"id": 81, "approx_ts": 222.5, "name": "Thunder Strike / Crack", "filename": "81_thunder_strike.mp3", "cat": "Impact"},
    {"id": 82, "approx_ts": 224.3, "name": "Whip Crack / Slap", "filename": "82_whip_crack_slap.mp3", "cat": "Impact"},
    {"id": 83, "approx_ts": 226.9, "name": "What The Dog Doin", "filename": "83_what_the_dog_doin.mp3", "cat": "Voice Meme"},
    {"id": 84, "approx_ts": 228.4, "name": "Why Are You Gay", "filename": "84_why_are_you_gay.mp3", "cat": "Voice Meme"},
    {"id": 85, "approx_ts": 230.5, "name": "Drum Roll", "filename": "85_drum_roll.mp3", "cat": "Music / Riff"},
    {"id": 86, "approx_ts": 232.5, "name": "Glass Breaking / Crash", "filename": "86_glass_breaking_crash.mp3", "cat": "Impact"}
]

print(f"Total defined SFX: {len(sfx_definitions)}")
