"""Built-in Style Profiles defining visual identities for various video aesthetics."""

from ai_broll_autopilot.styles.base import StyleProfile

PROFILES = [
    # 1. SPORTS EDITORIAL (Bold, high-contrast, energetic, heavy borders, vibrant highlights)
    StyleProfile(
        id="sports_editorial",
        name="Sports Editorial",
        description="High-energy, high-contrast editorial look with bold typography and punchy highlights.",
        font_family="Montserrat",
        font_size=58,
        font_weight="bold",
        font_style="normal",
        primary_color="#FFFFFF",
        highlight_color="#FFDD00",  # Vivid sport gold
        upcoming_color="rgba(255, 255, 255, 0.7)",
        background_color="transparent",
        stroke_color="#000000",
        stroke_width=5,
        shadow_color="rgba(0, 0, 0, 0.9)",
        shadow_blur=8,
        caption_animation_style="word-highlight",
        caption_position="bottom",
        broll_cut_pacing="dynamic",
        default_broll_duration=2.2,
        zoom_intensity=1.07,
        transition_type="cut",
        sound_effects_enabled=True,
        bgm_ducking_volume=0.18,
    ),

    # 2. CLEAN PODCAST (Crisp, modern, readable, subtle glow, cyan accent)
    StyleProfile(
        id="clean_podcast",
        name="Clean Podcast",
        description="Modern and clean podcast layout with refined typography and soft modern highlights.",
        font_family="Inter",
        font_size=52,
        font_weight="bold",
        font_style="normal",
        primary_color="#FFFFFF",
        highlight_color="#00E5FF",  # Modern electric cyan
        upcoming_color="rgba(255, 255, 255, 0.65)",
        background_color="transparent",
        stroke_color="#111111",
        stroke_width=3,
        shadow_color="rgba(0, 0, 0, 0.6)",
        shadow_blur=6,
        caption_animation_style="word-highlight",
        caption_position="bottom",
        broll_cut_pacing="moderate",
        default_broll_duration=2.6,
        zoom_intensity=1.04,
        transition_type="cut",
        sound_effects_enabled=True,
        bgm_ducking_volume=0.15,
    ),

    # 3. BUSINESS EDITORIAL (Polished, executive, authoritative, gold/navy highlights)
    StyleProfile(
        id="business_editorial",
        name="Business Editorial",
        description="Polished executive styling with crisp typography and sophisticated gold accents.",
        font_family="Montserrat",
        font_size=50,
        font_weight="bold",
        font_style="normal",
        primary_color="#F8FAFC",
        highlight_color="#F59E0B",  # Warm amber gold
        upcoming_color="rgba(248, 250, 252, 0.6)",
        background_color="transparent",
        stroke_color="#0F172A",
        stroke_width=3,
        shadow_color="rgba(15, 23, 42, 0.8)",
        shadow_blur=6,
        caption_animation_style="word-highlight",
        caption_position="bottom",
        broll_cut_pacing="moderate",
        default_broll_duration=2.8,
        zoom_intensity=1.03,
        transition_type="cut",
        sound_effects_enabled=True,
        bgm_ducking_volume=0.12,
    ),

    # 4. DOCUMENTARY (Cinematic, refined, longer holds, subtle warmth)
    StyleProfile(
        id="documentary",
        name="Documentary & Narrative",
        description="Cinematic pacing, elegant serif/sans captions, and contemplative cutaways.",
        font_family="Georgia",
        font_size=46,
        font_weight="normal",
        font_style="italic",
        primary_color="#F3F4F6",
        highlight_color="#E2E8F0",
        upcoming_color="rgba(243, 244, 246, 0.5)",
        background_color="rgba(0, 0, 0, 0.4)",
        stroke_color=None,
        stroke_width=0,
        shadow_color="rgba(0, 0, 0, 0.7)",
        shadow_blur=4,
        caption_animation_style="none",
        caption_position="bottom",
        broll_cut_pacing="smooth",
        default_broll_duration=3.5,
        zoom_intensity=1.02,
        transition_type="crossfade",
        sound_effects_enabled=False,
        bgm_ducking_volume=0.20,
    ),

    # 5. GAMING FAST (Hyper-paced, neon green/magenta, bouncy captions, quick cuts)
    StyleProfile(
        id="gaming_fast",
        name="Gaming Fast",
        description="Rapid-fire gaming aesthetic with neon accents, bounce captions, and quick cuts.",
        font_family="Montserrat",
        font_size=60,
        font_weight="bold",
        font_style="normal",
        primary_color="#FFFFFF",
        highlight_color="#10B981",  # Neon emerald green
        upcoming_color="rgba(255, 255, 255, 0.8)",
        background_color="transparent",
        stroke_color="#000000",
        stroke_width=6,
        shadow_color="rgba(16, 185, 129, 0.6)",
        shadow_blur=10,
        caption_animation_style="bounce",
        caption_position="bottom",
        broll_cut_pacing="rapid",
        default_broll_duration=1.8,
        zoom_intensity=1.09,
        transition_type="cut",
        sound_effects_enabled=True,
        bgm_ducking_volume=0.25,
    ),

    # 6. NEWS EDITORIAL (Authoritative, red/white/yellow accents, breaking lower-thirds)
    StyleProfile(
        id="news_editorial",
        name="News Editorial",
        description="Broadcast and investigative styling with bold typography and prominent banners.",
        font_family="Arial",
        font_size=52,
        font_weight="bold",
        font_style="normal",
        primary_color="#FFFFFF",
        highlight_color="#EF4444",  # Bold news red
        upcoming_color="rgba(255, 255, 255, 0.7)",
        background_color="rgba(0, 0, 0, 0.65)",
        stroke_color=None,
        stroke_width=0,
        shadow_color="rgba(0, 0, 0, 0.8)",
        shadow_blur=5,
        caption_animation_style="word-highlight",
        caption_position="bottom",
        broll_cut_pacing="dynamic",
        default_broll_duration=2.5,
        zoom_intensity=1.04,
        transition_type="cut",
        sound_effects_enabled=True,
        bgm_ducking_volume=0.15,
    ),

    # 7. MINIMAL (Clean, low visual noise, pure white text, no outline, focus on content)
    StyleProfile(
        id="minimal",
        name="Minimal Clean",
        description="Ultra-clean, distraction-free aesthetic with subtle word-level highlighting.",
        font_family="Inter",
        font_size=48,
        font_weight="bold",
        font_style="normal",
        primary_color="#FFFFFF",
        highlight_color="#FBBF24",  # Soft warm yellow
        upcoming_color="rgba(255, 255, 255, 0.5)",
        background_color="transparent",
        stroke_color=None,
        stroke_width=0,
        shadow_color="rgba(0, 0, 0, 0.5)",
        shadow_blur=4,
        caption_animation_style="word-highlight",
        caption_position="bottom",
        broll_cut_pacing="moderate",
        default_broll_duration=2.5,
        zoom_intensity=1.03,
        transition_type="cut",
        sound_effects_enabled=False,
        bgm_ducking_volume=0.10,
    ),
]
